prometheus:
  server:
    persistentVolume:
      enabled: true
      storageClass: gp2
      size: 8Gi

  alertmanager:
    persistentVolume:
      enabled: true
      storageClass: gp2
      size: 2Gi

  pushgateway:
    enabled: false

  server:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi