# Prometheus lightweight values (Using emptyDir for test environment)
prometheus:
  server:
    retain_drop_markers: false
    persistentVolume:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  alertmanager:
    enabled: true
    persistence:
      enabled: false

  pushgateway:
    enabled: false
