# kube-prometheus-stack values
# This stack includes Prometheus, Grafana, Alertmanager, and Node Exporter

grafana:
  service:
    type: LoadBalancer
    port: 80

prometheus:
  prometheusSpec:
    # This helps in picking up PodMonitors from other namespaces
    podMonitorSelectorNilControls:
      enabled: true

alertmanager:
  enabled: true

# Ensure we have a clean install for the test environment
kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
